name: Build SDL CnC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Install SDL2
      run: vcpkg install sdl2:x86-windows

    - name: Configure
      run: cmake -B build -A Win32 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"

    - name: Build
      run: cmake --build build --config Release

    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: cnc-sdl-build
        path: build/Release
